name: CI

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "fastlane/**"
      - "inventory/**"
      - "repo_assets/**"
      - ".github/**"
      - "kotlin_code_style.xml"
  push:
    paths-ignore:
      - "**.md"
      - "fastlane/**"
      - "inventory/**"
      - "repo_assets/**"
      - ".github/**"
      - "kotlin_code_style.xml"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew assembleDebug

      - name: Find generated APK
        id: find_apk
        run: |
          APK_PATH=$(find app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          echo "apk-path=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: ${{ steps.find_apk.outputs.apk-path }}
